stages:
  - lint

eslint:
  image: 14.17.0-alpine
  stage: lint
  variables:
    NODE_VERSION: 14.17.0
  script:
    - npm install
    - npm run lint

prettier:
  image: 14.17.0-alpine
  stage: lint
  variables:
    NODE_VERSION: 14.17.0
  script:
    - npm install
    - npm run check:format
