stages:
#  - lint
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

# Alek
# before_script:
#   - npm ci --cache .npm --prefer-offline
# Alek add

variables:
  NODE_IMAGE: node:14.17.0-alpine
  SERVER_IP:  deploy@45.79.211.19

#eslint:
#  image: $NODE_IMAGE
#  stage: lint
 # script:
 #   - npm install
 #   - npm run lint

# prettier:
#   image: $NODE_IMAGE
#   stage: lint
#   script:
#     - npm install
#     - npm run check:format
#
deploy:
  image: ubuntu:latest
  stage: deploy
  script:
    - apt -qq update && apt upgrade -qqy openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - rsync -a --progress --human-readable --delete
      --exclude-from '.gitignore'
      --exclude .gitignore
      --exclude .git
      --exclude .npm
      --exclude public
      . deploy@45.79.211.19:~/realworld/
    - ssh deploy@45.79.211.19 "pushd ~/realworld && npm install && pm2 restart realworld && popd"