stages:
  - lint

cache:
  key:
    files:
      - package-lock.json
    path:
      - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

variables:
  NODE_VERSION: node:14.17.0-alpine

eslint:
  image: $NODE_VERSION
  stage: lint
  script:
    - npm install
    - npm run lint

prettier:
  image: $NODE_VERSION
  stage: lint
  script:
    - npm install
    - npm run check:format
